blank_issues_enabled: false
contact_links:
  - name: Questions or Support
    url: https://github.com/The-Node-Forge/community/discussions
    about: "Need help? Start a discussion with the community here."
