name: "Join the Forge"

on:
  issues:
    types:
      - opened

jobs:
  invite-user:
    if: startsWith(github.event.issue.title, 'Please invite me to the Forge')
    runs-on: ubuntu-latest
    steps:
      - name: Add user to the organization
        env:
          GH_TOKEN: ${{ secrets.ORG_INVITE_TOKEN }}
        run: |
          issue_user=${{ github.event.issue.user.login }}
          org_name="The-Node-Forge"

          echo "Inviting $issue_user to $org_name..."

          # Send invitation via GitHub API
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/$org_name/memberships/$issue_user \
            -d '{"role":"member"}'

      - name: Comment on issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          repo=${{ github.repository }}

          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$repo/issues/$issue_number/comments \
            -d '{"body":"You have been invited to join The-Node-Forge! Check your email to accept the invitation."}'
