name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # You can adjust this to your specific target branch like deployable or staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload test results (optional)
        if: failure()  # Upload test results only if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results  # Adjust this if needed
