name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to The Node Forge! Thanks for opening your first issue. Let us know how we can help!"
          pr-message: "🚀 Thanks for your first pull request! A reviewer will take a look soon."
